### ISSUE TITLE
Preparar modelos para integrar con base de datos

### ISSUE THREAD

**Issue by Tecnologer** [Tecnologer/ToDoList#5]
Agregar las propiedades correspondientes a los modelos para prepararlos para la integracion con la base de datos usando las siguientes propiedades:

## Modelos
- Usuario
  - ID
  - Nombre
  - Tareas :  arreglo de tareas
- Tarea
  - ID
  - ID de usuario
  - Descripcion
  - Status 
  - Fecha de creacion
  - Fecha de completado

**Comment by oscarCR19** [comment]
Buenas noches
Espero alguien me oriente, mi ticket dice que debo de implementar los siguientes atributos en las clases correspondientes y preparar para la db, solo tengo una duda, tomando en cuenta todo lo que hay en clases, seria implementar los métodos para extraer y insertar la informacion basandose en estos atributos.


Gracias.

**Comment by Tecnologer** [comment]
se requieren agregar/eliminar/renombrar las propiedades segun sea el caso de la clase, por ejemplo, se pide que Usuario debe de tener las siguientes propiedades:
- ID
- Nombre
- Tareas : arreglo de tareas

Pero la definicion actual ya tiene `Nombre` y `Tareas`, por lo que solo es necesario agregar la propiedad `ID`

**Comment by oscarCR19** [comment]
Listo vamos a implementar lo requerido.

Gracias compañero.
