### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by oscarCR19** [Tecnologer/ToDoList#7]
Buenas noches compañeros

He tratado de avanzar con mi parte del proyecto, hice la integración de lo faltante para iniciar con una db pero me faltó hacer el pull request, no supe como hacerlo, primero que todo aviso por si llegará a pasar algo en sus repositorios y segundo para saber si alguien me puede dar una pequeña asesoria.

Quedo a la espera.

**Comment by Tecnologer** [comment]
lo que paso es que subiste los cambios directamente a `master` y no al branch correspondiente a tu cambio
